(fix/avar_oval) : user avatar is oval )
XPEHO/MobileOne pull request #149
Opened 2020-08-07 08:55 UTC by zohra051

2020-08-10 12:36 UTC, nathanvandeperre97 submitted a review, later dismissed

2020-08-10 13:01 UTC, nathanvandeperre97 submitted a review, later dismissed

2020-08-10 16:03 UTC, nathanvandeperre97 commented on test/widgets/profile/gallery_test.dart
> +    //  verify(_prefService.setString("picture45", "assets/images/facebook_f.png"));
Why is the verify commented ?

2020-08-11 06:56 UTC, PiotrFLEURY requested changes

2020-08-11 06:56 UTC, PiotrFLEURY commented on test/widgets/profile/gallery_test.dart
> +    //  verify(_prefService.setString("picture45", "assets/images/facebook_f.png"));
+1 why did you comment this verify ?

2020-08-11 10:22 UTC, nathanvandeperre97 submitted a review, later dismissed

2020-08-11 13:06 UTC, nathanvandeperre97 submitted a review, later dismissed

2020-08-11 15:03 UTC, nathanvandeperre97 approved these changes

2020-08-11 15:13 UTC, PiotrFLEURY approved these changes

2020-08-11 15:13 UTC, merged