(fix/empty_LC_screen):added an empty screen to scan bar codes
XPEHO/MobileOne pull request #227
Opened 2020-08-26 09:29 UTC by zohra051

2020-08-26 15:13 UTC, nathanvandeperre97 requested changes
- The empty screen text is not centered, please center it.
- There is no changelog modifications, please add it.

2020-08-28 06:48 UTC, PiotrFLEURY approved these changes, later dismissed

2020-08-28 09:41 UTC, PiotrFLEURY approved these changes

2020-08-28 09:41 UTC, PiotrFLEURY requested changes
no changelog

2020-08-28 09:49 UTC, PiotrFLEURY submitted a review, later dismissed

2020-08-28 09:57 UTC, nathanvandeperre97 approved these changes, later dismissed

2020-08-28 12:09 UTC, nathanvandeperre97 approved these changes

2020-08-28 12:13 UTC, merged