Feat/create lists
XPEHO/MobileOne pull request #34
Opened 2020-06-16 09:08 UTC by zohra051

2020-06-16 09:51 UTC, nathanvandeperre97 requested changes
I still have a bug where I need to refresh the lists page to see my lists

2020-06-16 09:51 UTC, nathanvandeperre97 commented on lib/pages/Mainpage.dart
> -      key: Key("Mainn"),
Why is the key Mainn and not Main ?

2020-06-16 09:51 UTC, nathanvandeperre97 commented on resources/lang/fr.json
> +    "shared_with_me": "Shared with me : ",
English sentence in French json

2020-06-16 10:06 UTC, nathanvandeperre97 submitted a review, later dismissed

2020-06-16 12:11 UTC, nathanvandeperre97 submitted a review, later dismissed

2020-06-16 13:19 UTC, PiotrFLEURY requested changes

2020-06-16 13:19 UTC, PiotrFLEURY commented on lib/main.dart
> +  /*final FirebaseApp app = await FirebaseApp.configure(
Remove this comment please

2020-06-16 13:19 UTC, PiotrFLEURY commented on lib/main.dart
> +            googleAppID: "1:247649689994:ios:c93c27507d2cd4bacca873",
Never commit Firebase informations in sources

2020-06-16 13:19 UTC, PiotrFLEURY commented on lib/main.dart
> +void main() async {
main function should not be async

2020-06-16 13:19 UTC, PiotrFLEURY commented on lib/pages/create_list.dart
> +    Lists();
remove this useless line

2020-06-16 13:19 UTC, PiotrFLEURY commented on lib/pages/create_list.dart
> +    widgetList.add(patternLists(context));
what is that ? where does it come from ? Why don't you use provider to share data bewteen screens ?

2020-06-16 13:19 UTC, PiotrFLEURY commented on lib/pages/lists.dart
> +final List<Widget> widgetList = [];
Avoid creating global list of widgets

2020-06-16 13:19 UTC, PiotrFLEURY commented on lib/pages/lists.dart
> +                  children: widgetList,
use a provider of data instead of global list of widgets

2020-06-16 13:19 UTC, PiotrFLEURY commented on lib/pages/pattern_list.dart
> +Widget patternLists(BuildContext context) {
What is this file ? Is that a widget ? Is that a function ? Is that anything else ?

If you want to create a specific widget just create a Widget. Not a function that will generate a Widget

2020-06-16 13:19 UTC, PiotrFLEURY commented on lib/pages/pattern_list.dart
> +                "Example",
hard coded string

2020-06-16 13:19 UTC, PiotrFLEURY commented on lib/pages/pattern_list.dart
> +              "Example",
hard coded string

2020-06-23 14:12 UTC, PiotrFLEURY requested changes
Please consider requested changes

2020-06-23 14:12 UTC, PiotrFLEURY commented on lib/main.dart
> +void main() async {
please remove the async keyword

2020-06-23 14:12 UTC, PiotrFLEURY commented on lib/pages/Mainpage.dart
> +    print("IM HERE MAINPAGE");
remove useless print

2020-06-23 14:12 UTC, PiotrFLEURY commented on lib/pages/Mainpage.dart
> +    Navigator.of(context).push(
replace it by a Navigator.of(context).pushNamed("/createList");

2020-06-23 14:12 UTC, PiotrFLEURY commented on lib/pages/create_list.dart
> +      'itemCounts': itemCounts.toString(),
assumine thae you are creating a new wishlist it will be empty so you can specify "0" and remove int itemCounts = 0; at line 11

2020-06-23 14:12 UTC, PiotrFLEURY commented on lib/pages/create_list.dart
> +    print("IM HERE CREATE LISTS");
remove useless print

2020-06-23 14:12 UTC, PiotrFLEURY commented on lib/pages/widget_list.dart
> +      label = labelValue;
you can group Future<void> getListLabel() and Future<void> getListItemCount() in one method Future<void> getListDetails() and make only one setState at the end

2020-06-23 14:12 UTC, PiotrFLEURY commented on lib/services/database_service.dart
> +class ListsService with ChangeNotifier {}
delete this useless class

2020-06-23 14:31 UTC, PiotrFLEURY requested changes
Please consider requested changes

2020-06-23 14:31 UTC, PiotrFLEURY commented on lib/pages/lists.dart
> +        if (snapshot.data.data["lists"] != null) {
snapshot.data.data may be null on first connection 

you can replace by 

var wishlist = snapshot?.data?.data?.get("lists") ?? [];

2020-06-23 14:31 UTC, PiotrFLEURY commented on lib/pages/lists.dart
> +String numberOfItemShared = "3 partages";
hard coded string. please use getString()

2020-06-23 14:31 UTC, PiotrFLEURY commented on lib/pages/widget_list.dart
> +    await Firestore.instance
group the two Firebase call in one

await Firestore.instance
        .collection("wishlists")
        .document(_listUuid)
        .get()
        .then((value) { 
            labelValue = value["label"];
            countValue = value["itemCounts"];
});

2020-06-23 15:00 UTC, PiotrFLEURY submitted a review, later dismissed
LGTM !

2020-06-23 15:37 UTC, nathanvandeperre97 approved these changes

2020-06-23 16:03 UTC, merged