Feat/share list
XPEHO/MobileOne pull request #42
Opened 2020-07-06 12:42 UTC by zohra051

2020-07-07 07:20 UTC, PiotrFLEURY requested changes

2020-07-07 07:20 UTC, PiotrFLEURY commented on .gitignore
> +android/app/
replace this line by android/app/bin/

2020-07-08 09:49 UTC, PiotrFLEURY requested changes

2020-07-08 09:49 UTC, PiotrFLEURY commented on lib/pages/share_one.dart
> +                      contactSelected = contacts[index];
there is a bug here. You should put contact into contactSelected instead of contacts[index]

2020-07-08 09:49 UTC, PiotrFLEURY commented on lib/pages/share_two.dart
> +       // _labels.forEach((element) {_lists.add(element);});
remove commented code

2020-07-08 09:49 UTC, PiotrFLEURY commented on lib/pages/share_two.dart
> +        print("la liste filtré");
remove all print please

2020-07-08 09:49 UTC, PiotrFLEURY commented on lib/pages/share_two.dart
> +                            print("et les labels ici ça donne quoi ? ");
please remove print

2020-07-08 09:49 UTC, PiotrFLEURY commented on lib/pages/share_two.dart
> +                          print("la taille de la liste filtré");
remove all print

2020-07-08 09:49 UTC, PiotrFLEURY commented on lib/pages/share_two.dart
> +    Navigator.of(context).pop();
should use Navigator.popUntil(context, ModalRoute.withName('route name'));

2020-07-08 09:49 UTC, PiotrFLEURY commented on lib/utility/mock.dart
> +import 'package:MobileOne/providers/share_provider.dart';
wrong place wrong content

this file should contain all

MonMock extends Mock implements Maclasse {}

and be located in the test folder

2020-07-08 11:57 UTC, zohra051 commented on lib/pages/share_one.dart
> +                      contactSelected = contacts[index];
please see after

2020-07-09 06:31 UTC, PiotrFLEURY requested changes

2020-07-09 06:31 UTC, PiotrFLEURY commented on lib/pages/share_two.dart
> +                              if (searchTermEmail != null) {
avoid making reference to a var from another file. You should set this variable as a parameter of ShareTwo() with 

`Navigator.of(context).pushNamed("/shareTwo", parameters: searchTermEmail);` 

and fetch it in ShareTwo build method like this: 

`String searchTermEmail = ModaleRoute.of(context).settings.parameters;`

2020-07-09 06:31 UTC, PiotrFLEURY commented on lib/pages/share_two.dart
> +                                    contactSelected.emails.elementAt(0).value,
Bug here. If the selected contact does not have any email this line throws an Exception. You should be sure to filter contacts of ShareOne with only contacts with an email.

2020-07-09 06:31 UTC, PiotrFLEURY commented on lib/widgets/widget_share_lists.dart
> +                                  onTap: () {},
Missing revoke share action. Please implement wishlist share revocation

2020-07-09 11:50 UTC, PiotrFLEURY approved these changes
LGTM !

2020-07-09 11:50 UTC, merged