Feat/new change profile picture
XPEHO/MobileOne pull request #62
Opened 2020-07-21 15:45 UTC by zohra051

2020-07-21 15:50 UTC, PiotrFLEURY requested changes

2020-07-21 15:50 UTC, PiotrFLEURY commented on test_driver/app_test.dart
> +/*import 'package:MobileOne/pages/authentication-page.dart';
no no no, it's too easy to comment a test like this. You have to make a choice : 
1- Delete the test because it is outdated
2- Fix the test

2020-07-22 12:08 UTC, nathanvandeperre97 submitted a review, later dismissed
LGTM

2020-07-23 06:55 UTC, PiotrFLEURY approved these changes

2020-07-23 06:56 UTC, merged